config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
#create
   get "tasks/new", to: "tasks#new"
   post "tasks", to: "tasks#create"
   
   #update
   get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
   patch "tasks/:id", to: "tasks#update"
   
   #read
     get "tasks", to: "tasks#index"
     get "tasks/:id", to: "tasks#show", as: "task"

     #delete
     delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def new
        @task =Task.new
    end
    
    def create 
        @task = Task.new(task_params)
        @task.save 
        redirect_to tasks_path(@task)
    end
    
    def show 
        @task = Task.find(params[:id])
    end
    
    def index
        @tasks = Task.all   
    end   

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(task_params) 
        redirect_to tasks_path(@task)
      end

      def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_path(@task), status: :see_other
      end

end
  
private
  
  def task_params
    params.require(:task).permit(:title, :details)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %>
  <%= f.label :Details %>
  <%= f.text_field :details %>
  <%= f.submit "Update Task" %>
<% end %>

app/views/tasks/index.html.erb
<div class="cointainer mt-5">>
<h1> My Task </h1>
<ul>
  <% @tasks.each do |task| %> 
    <li>     
    <%= task.title %><br><%= link_to "🗑️",
  task_path(task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
 %>
    </li>
  <% end %>

<%= link_to "Add new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %>
  <%= f.label :Details %>
  <%= f.text_field :details %>
  <%= f.submit "Create Task" %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>

<% if @task.completed == true %>
  <p> This task is completed </p>
 <% else %>
  <p> This task is not completed </p>
<% end %>

<%= link_to "Edit Task", task_edit_path %>

<%= link_to "Back to home", tasks_path %>